footprint: [[-0.4, -0.4], [-0.4, 0.4], [0.4, 0.4], [0.4, -0.4]]
footprint_padding: 0.03

robot_base_frame: base_link
#robot_base_frame: base_footprint
update_frequency: 4
#update_frequency: 1
publish_frequency: 4
#publish_frequency: 3
transform_tolerance: 0.5
resolution: 0.05

obstacle_range: 2.5
raytrace_range: 2.5

### Sensor management parameters

#observation_sources: scan
#scan:
#    topic: /robot/scan
#    sensor_frame: front_laser
#    data_type: LaserScan
#    clearing: true
#    marking: true
#    inf_is_valid: true # real
#    min_obstacle_height: 1
#    max_obstacle_height: 5
#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: robot/scan/filtered, inf_is_valid: true, sensor_frame: front_laser}

inflation:
    inflation_radius: 2.0
    cost_scaling_factor: 1.7
